"""Generate a markdown plan file for a set of asset conversions."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import yaml

from .estimator import SizeEstimate, estimate, total_savings
from .scanner import AssetFile


def _fmt_kb(size_bytes: int) -> str:
    kb = size_bytes / 1024
    if kb >= 1024:
        return f"{kb / 1024:.2f} MB"
    return f"{kb:.1f} KB"


def build_plan(
    assets: list[AssetFile],
    quality: int,
    root: Path,
) -> tuple[str, str]:
    """Generate a plan markdown string and a suggested filename.

    Returns:
        (markdown_content, filename)
    """
    timestamp = datetime.now()
    ts_str = timestamp.strftime("%Y%m%d_%H%M%S")
    ts_display = timestamp.strftime("%Y-%m-%d %H:%M:%S")
    filename = f"plan_{ts_str}.md"

    estimates: list[tuple[AssetFile, SizeEstimate]] = [
        (asset, estimate(asset)) for asset in assets
    ]

    # Machine-readable front-matter: store paths relative to root so the plan
    # is portable and human-friendly.
    front: dict = {
        "quality": quality,
        "root": str(root),
        "files": [str(asset.path) for asset, _ in estimates],
    }

    lines: list[str] = []
    lines.append("---")
    lines.append(yaml.dump(front, default_flow_style=False, allow_unicode=True).rstrip())
    lines.append("---")
    lines.append("")
    lines.append(f"## webpconverter plan — {ts_display}")
    lines.append("")

    # Summary totals
    total_orig, total_est, total_pct = total_savings([est for _, est in estimates])
    lines.append(
        f"> **{len(assets)} files** scanned — "
        f"total original: **{_fmt_kb(total_orig)}** — "
        f"estimated after conversion: **{_fmt_kb(total_est)}** — "
        f"estimated saving: **{total_pct:.1f}%**"
    )
    lines.append("")
    lines.append(f"> WebP quality setting: **{quality}**")
    lines.append("")

    # Table header
    lines.append("| # | File | Type | Current Size | Est. WebP Size | Est. Saving | Est. Load Gain |")
    lines.append("|---|------|------|-------------|----------------|-------------|----------------|")

    for idx, (asset, est) in enumerate(estimates, start=1):
        try:
            rel = asset.path.relative_to(root)
        except ValueError:
            rel = asset.path

        gain_ms = est.estimated_loading_gain_ms
        gain_str = f"{gain_ms:.1f} ms" if gain_ms < 1000 else f"{gain_ms / 1000:.2f} s"

        lines.append(
            f"| {idx} "
            f"| `{rel}` "
            f"| {asset.format_label} "
            f"| {_fmt_kb(est.original_bytes)} "
            f"| {_fmt_kb(est.estimated_bytes)} "
            f"| {est.saving_pct:.1f}% "
            f"| {gain_str} |"
        )

    lines.append("")
    lines.append("---")
    lines.append(
        "_Generated by webpconverter. "
        "Run `webpconverter exec <this file>` to perform the conversions._"
    )
    lines.append("")

    return "\n".join(lines), filename


def write_plan(
    assets: list[AssetFile],
    quality: int,
    root: Path,
    output_dir: Path | None = None,
) -> Path:
    """Write the plan markdown file and return its path."""
    content, filename = build_plan(assets, quality, root)
    out_dir = output_dir or Path.cwd()
    out_dir.mkdir(parents=True, exist_ok=True)
    plan_path = out_dir / filename
    plan_path.write_text(content, encoding="utf-8")
    return plan_path


def load_plan(plan_path: Path) -> tuple[list[str], int]:
    """Parse a plan file and return (file_paths, quality).

    Reads only the YAML front-matter block delimited by ``---``.
    """
    text = plan_path.read_text(encoding="utf-8")
    lines = text.splitlines()

    if not lines or lines[0].strip() != "---":
        raise ValueError(f"Plan file does not start with YAML front-matter: {plan_path}")

    end_idx = next(
        (i for i, line in enumerate(lines[1:], start=1) if line.strip() == "---"),
        None,
    )
    if end_idx is None:
        raise ValueError(f"Unclosed YAML front-matter in plan file: {plan_path}")

    yaml_text = "\n".join(lines[1:end_idx])
    data = yaml.safe_load(yaml_text)

    files: list[str] = data.get("files", [])
    quality: int = int(data.get("quality", 85))

    return files, quality
