"""Generate convert_report.md after a batch conversion run."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .converter import ConversionResult


def _fmt_kb(size_bytes: int) -> str:
    kb = size_bytes / 1024
    if kb >= 1024:
        return f"{kb / 1024:.2f} MB"
    return f"{kb:.1f} KB"


def build_report(
    results: list[ConversionResult],
    plan_path: Path,
    quality: int,
) -> str:
    """Return the full markdown content of the conversion report."""
    ts_display = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    succeeded = [r for r in results if r.success]
    failed = [r for r in results if not r.success]

    total_orig = sum(r.original_bytes for r in succeeded)
    total_conv = sum(r.converted_bytes for r in succeeded)
    total_saved = total_orig - total_conv
    total_pct = (total_saved / total_orig * 100) if total_orig else 0.0

    lines: list[str] = []
    lines.append(f"## webpconverter report — {ts_display}")
    lines.append("")
    lines.append(f"> Plan file: `{plan_path.name}`  ")
    lines.append(f"> WebP quality: **{quality}**  ")
    lines.append(
        f"> Results: **{len(succeeded)} converted**, **{len(failed)} failed** "
        f"out of {len(results)} total"
    )
    lines.append("")

    if succeeded:
        lines.append(
            f"> Total size before: **{_fmt_kb(total_orig)}** → "
            f"after: **{_fmt_kb(total_conv)}** — "
            f"saved **{_fmt_kb(total_saved)}** ({total_pct:.1f}%)"
        )
        lines.append("")
        lines.append("### Converted files")
        lines.append("")
        lines.append("| # | Source | WebP Output | Before | After | Saving |")
        lines.append("|---|--------|-------------|--------|-------|--------|")

        for idx, r in enumerate(succeeded, start=1):
            if r.saving_pct < 0:
                saving_str = f"⚠ +{abs(r.saving_pct):.1f}% (larger — consider keeping original)"
            else:
                saving_str = f"{r.saving_pct:.1f}%"
            lines.append(
                f"| {idx} "
                f"| `{r.source_path}` "
                f"| `{r.output_path}` "
                f"| {_fmt_kb(r.original_bytes)} "
                f"| {_fmt_kb(r.converted_bytes)} "
                f"| {saving_str} |"
            )

        lines.append("")
        lines.append("### Output paths (for AI reference)")
        lines.append("")
        lines.append(
            "_Copy this block and paste it into your AI chat to update "
            "all asset references in the project._"
        )
        lines.append("")
        lines.append("```")
        for r in succeeded:
            lines.append(str(r.output_path))
        lines.append("```")
        lines.append("")

    if failed:
        lines.append("### Failed conversions")
        lines.append("")
        lines.append("| # | Source | Error |")
        lines.append("|---|--------|-------|")

        for idx, r in enumerate(failed, start=1):
            error_escaped = r.error.replace("|", "\\|")
            lines.append(
                f"| {idx} | `{r.source_path}` | {error_escaped} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("_Generated by webpconverter._")
    lines.append("")

    return "\n".join(lines)


def write_report(
    results: list[ConversionResult],
    plan_path: Path,
    quality: int,
    output_dir: Path | None = None,
) -> Path:
    """Write ``convert_report.md`` next to the plan file and return its path."""
    content = build_report(results, plan_path, quality)
    out_dir = output_dir or plan_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / "convert_report.md"
    report_path.write_text(content, encoding="utf-8")
    return report_path
